apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-demo-deployment
  namespace: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: my-c1
        image: nginx:latest
        ports:
        - containerPort: 80
